services:
  aiopicks:
    container_name: aiopicks
    image: ghcr.io/madswami53/aiopicks:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped